name: GitHub Actions Demo
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
    build:
        # ...
        runs-on: ubuntu-latest
        steps:

         - name: Check out the repo
           uses: actions/checkout@v2

         - name: Get short SHA
           run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

         - name: Build
           uses: docker/build-push-action@v2
           with:
             tags: infosecjulia8/my-tweet-app-lacework:${{ env.GHA_SHA }},infosecjulia8/my-tweet-app-lacework:latest
             load: true

         - name: lw-scanner
           uses: lacework/lw-scanner-action@v0.6.0
           env:
             LW_SCANNER_SAVE_RESULTS: true
             LW_SCANNER_SCAN_LIBRARY_PACKAGES: true
             LW_SCANNER_DISABLE_UPDATES: true
           with:
             LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
             LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
             image_name: infosecjulia8/my-tweet-app-lacework
             image_tag: ${{ env.GHA_SHA }}
             BUILD_REPORT_FILE_NAME: true
             USE_POLICY: true
   
         - name: Login to DockerHub
           uses: docker/login-action@v1
           with:
             username: ${{ secrets.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}

         - name: tag and push
           uses: docker/build-push-action@v2
           with:
             push: true
             tags: infosecjulia8/my-tweet-app-lacework:${{ env.GHA_SHA }},infosecjulia8/my-tweet-app-lacework:latest,infosecjulia8/my-tweet-app-lacework:production

         - name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: us-west-1

         - name: deploy to cluster
           uses: kodermax/kubectl-aws-eks@master
           env:
             AWS_DEFAULT_REGION: us-west-1
             AWS_REGION: us-west-1
             KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
           with:
             args: set image deployment/my-tweet-app my-tweet-app=infosecjulia8/my-tweet-app-lacework:${{ env.GHA_SHA }} -n my-tweet-app

         - name: verify deployment
           uses: kodermax/kubectl-aws-eks@master
           env:
             AWS_DEFAULT_REGION: us-west-1
             AWS_REGION: us-west-1
             KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
           with:
             args: rollout status deployment/my-tweet-app -w -n my-tweet-app
